sudo: required
language: generic
matrix:
    include:
        # Use generic language for osx
        # disabled due to premake bug
        - os: osx
          osx_image: xcode8
          language: generic    
          env: TYPE=release ARCH=x86   
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=debug ARCH=x86
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=release ARCH=x86_64
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=debug ARCH=x86_64
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty
          env: TYPE=release ARCH=x86 VERSION=6
        - os: linux
          dist: trusty
          env: TYPE=debug ARCH=x86 VERSION=6
        - os: linux
          dist: trusty
          env: TYPE=release ARCH=x86_64 VERSION=6
        - os: linux
          dist: trusty
          env: TYPE=coverage ARCH=x86_64 VERSION=6
        - os: linux
          dist: trusty
          env: TYPE=debug ARCH=x86_64 VERSION=6
        - os: linux
          dist: trusty
          env: TYPE=release VERSION=5 ARCH=x86_64
        - os: linux
          dist: trusty
          env: TYPE=release VERSION=6 ARCH=x86_64
        - os: linux
          dist: trusty
          env: TYPE=zpm VERSION=6
install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
    # annoying pip fix
    - export BOTO_CONFIG=/tmp/bogusvalue
script:
    - bash script/travis-build.sh
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_OS_NAME" == "linux" ]]; then bash script/deploy-docs.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TYPE" = "coverage" ]]; then codecov; fi    