sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty
        # Use generic language for osx
        # disabled due to premake bug
        - os: osx
          osx_image: xcode8
          language: generic
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - rm -rf ~/.matplotlib/fontList.cache
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
    # annoying pip fix
    - export BOTO_CONFIG=/tmp/bogusvalue
script:
    - bash script/travis-build.sh
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash script/deploy-docs.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./script/coverage.sh; fi    